services:
  app:
    build:
      context: .
      dockerfile: DockerContainer_NodeJS.dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root